### ISSUE TITLE
Error "received unexpected message :_read_attribute" with rails 4-2-stable branch

### ISSUE THREAD

**Issue by kommen** [rspec/rspec-activemodel-mocks#11]
I'm getting this error when using `mock_model` with the current rails 4-2-stable branch:
```
 Double "User_1004" received unexpected message :_read_attribute with ("id")
```
It works as expected with rails 4.2.0.

I tracked the change introducing the incompatibility down to https://github.com/rails/rails/commit/be2b98b4ae3397149b713b774e415143c88c4fb7

**Comment by jdelStrother** [comment]
This should fix it - https://github.com/rspec/rspec-activemodel-mocks/pull/10

**Comment by JonRowe** [comment]
Fixed by #19

**Comment by JonRowe** [comment]
Now released

**Comment by scottbarrow** [comment]
I am getting this with Rails 4.2.8, and Composite Primary Keys 8.1.5. 
It seems that CPK is calling the `read_attribute` method. Is this something that should be handled within rspec-activemodel-mocks or CPK?

**Comment by JonRowe** [comment]
This is for a different method `_read_attribute` not `read_attribute`, it could be handled here but this gem is not intended to stub out every method within active record so it's probably easier if you do it within your project.
