### ISSUE TITLE
Release 1.0.2

### ISSUE THREAD

**Issue by JonRowe** [rspec/rspec-activemodel-mocks#21]
Can someone who has a key setup and access to rubygems release this? @rspec/rspec

**Comment by aprescott** [comment]
Anyone? @myronmarston?

**Comment by myronmarston** [comment]
Sorry, I'm on vacation traveling around Europe right now...

**Comment by JonRowe** [comment]
I think this might have to be @thomas-holmes looking at Rubygems..

**Comment by thomas-holmes** [comment]
I don't think this gem is signed. I'm happy to tag and release the current master (tonight).

**Comment by thomas-holmes** [comment]
Oh I see, but I'm the owner so maybe I'm the only one who can push...

It's been a while since I've done this :fearful:

**Comment by alindeman** [comment]
It probably makes sense to add a few more owners on rubygems.org? Maybe @myronmarston and @JonRowe at least?

**Comment by thomas-holmes** [comment]
Yeah, I'm gonna do that. I'm just moving really slowly right now so I don't foul up :)

**Comment by thomas-holmes** [comment]
OK. I've published current master as 1.0.2 and added myron and john as owners.

**Comment by bquorning** [comment]
:sparkles: Thank you @thomas-holmes :sparkles:
