### ISSUE TITLE
Implement lock! on instances

### ISSUE THREAD

**Issue by DanielHeath** [rspec/rspec-activemodel-mocks#40]
Anyone using https://api.rubyonrails.org/classes/ActiveRecord/Locking/Pessimistic.html is going to have to manually stub `lock!` - would be good to automatically stub builtin rails methods like this.

**Comment by JonRowe** [comment]
:wave: Thanks for the suggestion, this gem exists to support compatibility with ActiveModel, not the more specific ActiveRecord methods, theres a whole suite of methods that are not automatically mocked. 

The gem is also not under active development having been extracted from RSpec previously, if you'd like to take it on shout out and we can sort something out, else I'll close this as is.

**Comment by DanielHeath** [comment]
No problem, thanks for the info & supporting it thus far.
