### ISSUE TITLE
Rails 7.1: mock_model is not === the class it mocks

### ISSUE THREAD

**Issue by DanielHeath** [rspec/rspec-activemodel-mocks#54]
After upgrading to rails 7.1, `mock_model` instances are no longer considered to be instances of the model class in switch statements.

For instance, the following code breaks in 7.1
```
case mock_model("Article")
when Article then puts "correct"
else puts "incorrect"
end
```

**Comment by DanielHeath** [comment]
```
  $ ruby -v
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
```

Versions:

rails 7.1.2, rspec-core 3.12.2, rspec-mocks 3.12.6

**Comment by DanielHeath** [comment]
Full reproduction script:
```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  gem "sqlite3"
  gem "rspec-activemodel-mocks"
  gem "rspec"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

require "rspec/autorun"

RSpec.describe "the bug" do
  it "is convenient for self-contained examples & bug repros" do
    (Post === mock_model(Post)) || (raise "Why not")
  end
end

```

**Comment by DanielHeath** [comment]
(This test passes if you change rails version to `'6.1.7.6'`

**Comment by JonRowe** [comment]
Thats not surprising that (https://github.com/rails/rails/commit/31482d286790587a906c52ababf2e354fc2d460f) prevents case statements since it is "the classes" `===` that performs such checks, its not something the mock directly controls, can you give #55 a go to see if it meets your needs, I think its probably the simplist solution rather than any other kind of monkey patching....

Theres a couple of other failing specs on 7.1 as well so YMMV using this library on Rails 7.1

**Comment by DanielHeath** [comment]
That looks like it should work, thanks! Other than that everything appears to be working for me (on a sprawling 15yo rails codebase which uses mock_model pretty extensively).
